document.addEventListener('DOMContentLoaded',function(){
 var page=location.pathname.split('/').pop()||'index.html';
 var nav=document.querySelector('nav'),links=nav&&nav.querySelector('.links');
 if(links&&!links.querySelector('a[href="cars-for-sale.html"]')){var sale=document.createElement('a');sale.href='cars-for-sale.html';sale.textContent='CARS FOR SALE';var shop=links.querySelector('a[href="shop.html"]');if(shop)links.insertBefore(sale,shop);else links.appendChild(sale)}
 if(links)links.querySelectorAll('a[href="vehicle-intake.html"],a[href="sell-your-car.html"]').forEach(function(a){a.remove()});
 if(nav&&links){var button=document.createElement('button');button.className='mobile-toggle';button.type='button';button.setAttribute('aria-label','Open navigation');button.setAttribute('aria-expanded','false');button.innerHTML='<span></span><span></span><span></span>';nav.appendChild(button);function closeMenu(){links.classList.remove('open');document.body.classList.remove('menu-open');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open navigation')}button.addEventListener('click',function(){var open=!links.classList.contains('open');links.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close navigation':'Open navigation')});links.querySelectorAll('a').forEach(function(a){a.addEventListener('click',closeMenu)});window.addEventListener('resize',function(){if(innerWidth>800)closeMenu()});document.addEventListener('keydown',function(e){if(e.key==='Escape')closeMenu()})}
 if(page==='builds.html')document.querySelectorAll('a[href="build-gti.html"] img').forEach(function(img){img.src='2024-vw-gti-final-1.jpeg';img.alt='Finished blue 2024 Volkswagen GTI Autobahn'});
 var galleryPages=['build-gti.html','vehicle-listing-gti.html','vehicle-listing-hyundai-elantra-gt.html'];
 if(page==='build-gti.html'){var hero=document.querySelector('.hero-image');if(hero){hero.src='2024-vw-gti-final-1.jpeg';hero.alt='Finished blue 2024 Volkswagen GTI Autobahn'}}
 if(galleryPages.indexOf(page)>-1){if(!document.querySelector('link[href="vehicle-gallery.css"]')){var css=document.createElement('link');css.rel='stylesheet';css.href='vehicle-gallery.css';document.head.appendChild(css)}if(!document.querySelector('script[src="vehicle-gallery.js"]')){var script=document.createElement('script');script.src='vehicle-gallery.js';script.defer=true;document.body.appendChild(script)}}
 if(page==='cars-for-sale.html'){
   var inventory=document.querySelector('.inventory-grid');
   if(inventory&&!inventory.querySelector('a[href="vehicle-listing-hyundai-elantra-gt.html"]')){
     var elantra=document.createElement('article');
     elantra.className='vehicle';
     elantra.innerHTML='<a class="media" href="vehicle-listing-hyundai-elantra-gt.html"><img src="2018-hyundai-elantra-gt-final-012.jpeg" alt="2018 Hyundai Elantra GT"><span class="badge">DETAILS PENDING</span><span class="docbadge">PHOTO ARCHIVE</span></a><div class="body"><div class="kicker">LAKACHE INVENTORY / 003</div><h3>2018 Hyundai<br>Elantra GT</h3><p>A detailed visual record of the finished Elantra GT, with exterior, interior and condition photography available in the complete vehicle gallery.</p><div class="facts"><div class="fact"><small>YEAR</small><strong>2018</strong></div><div class="fact"><small>MODEL</small><strong>Elantra GT</strong></div><div class="fact"><small>DETAILS</small><strong>Pending verification</strong></div></div><div class="actions"><a class="btn" href="vehicle-listing-hyundai-elantra-gt.html">VIEW ELANTRA GT →</a><a class="btn alt" href="vehicle-listing-hyundai-elantra-gt.html">VIEW PHOTO ARCHIVE</a></div></div>';
     inventory.appendChild(elantra);
     var count=document.querySelector('.inventory-bar .count');if(count)count.innerHTML='<b>03</b> VEHICLES CURRENTLY LISTED';
   }
 }
 var vehicleCatalog={gti:{name:'2024 Volkswagen GTI Autobahn',short:'THE GTI',subject:'2024 VW GTI Autobahn - Buyer Inquiry',question:'Questions about the GTI:'},bmw550i:{name:'2016 BMW 550i M Sport',short:'THE BMW 550i',subject:'2016 BMW 550i M Sport - Buyer Inquiry',question:'Questions about the BMW 550i:'},elantra:{name:'2018 Hyundai Elantra GT',short:'THE ELANTRA GT',subject:'2018 Hyundai Elantra GT - Buyer Inquiry',question:'Questions about the Elantra GT:'}};
 var pageVehicle=(page==='vehicle-listing-gti.html'||page==='vehicle-listing-gti-demo.html')?'gti':page==='vehicle-listing-bmw-550i.html'?'bmw550i':page==='vehicle-listing-hyundai-elantra-gt.html'?'elantra':'';
 if(pageVehicle)document.querySelectorAll('a[href="contact.html"]').forEach(function(a){if(a.closest('.cta')||/ASK ABOUT/i.test(a.textContent||''))a.href='contact.html?vehicle='+encodeURIComponent(pageVehicle)+'#vehicle-inquiry'});
 if(page==='contact.html'){var key=new URLSearchParams(location.search).get('vehicle'),vehicle=vehicleCatalog[key],buyer=document.querySelector('#vehicle-inquiry');if(buyer){var vehicleBox=buyer.querySelector('.vehicle'),buyerCopy=buyer.querySelector('.buyer-copy'),mailbtn=buyer.querySelector('.mailbtn');if(vehicle){if(vehicleBox){var small=vehicleBox.querySelector('small'),strong=vehicleBox.querySelector('strong');if(small)small.textContent='VEHICLE INQUIRY';if(strong)strong.textContent=vehicle.name}if(buyerCopy)buyerCopy.textContent='Send the basics that help us respond intelligently. The vehicle is already identified in the email subject so your inquiry does not get mixed in with general messages.';if(mailbtn){var body='Name:\n\nPhone:\n\nLocation:\n\nBuying timeline:\n\nCash / Financing / Undecided:\n\nTrade-in (if any):\n\n'+vehicle.question+'\n';mailbtn.href='mailto:info@lakacheauto.com?subject='+encodeURIComponent(vehicle.subject)+'&body='+encodeURIComponent(body);mailbtn.textContent='ASK ABOUT '+vehicle.short+' →'}}else if(mailbtn){mailbtn.href='mailto:info@lakacheauto.com?subject='+encodeURIComponent('Lakache Auto - Vehicle Buyer Inquiry');mailbtn.textContent='VEHICLE INQUIRY →'}}}
 document.querySelectorAll('a[href^="mailto:info@lakache.com"]').forEach(function(a){a.href=a.href.replace('info@lakache.com','info@lakacheauto.com')});
 document.querySelectorAll('footer').forEach(function(footer){footer.innerHTML=footer.innerHTML.replace(/CARS\s*(?:•|·)\s*BUILDS?\s*(?:•|·)\s*LIFE/gi,'CARS BUILD LIFE').replace(/CARS\s+BUILDS?\s+LIFE/gi,'CARS BUILD LIFE')});
 document.querySelectorAll('a[target="_blank"]').forEach(function(a){var rel=(a.getAttribute('rel')||'').split(/\s+/).filter(Boolean);if(rel.indexOf('noopener')<0)rel.push('noopener');a.setAttribute('rel',rel.join(' '))});
 if(nav)nav.querySelectorAll('a').forEach(function(a){var href=a.getAttribute('href');if(href===page)a.setAttribute('aria-current','page')});
 function redPeriod(el){if(!el||el.querySelector('.brand-period'))return;var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),nodes=[],n;while(n=w.nextNode())nodes.push(n);for(var i=nodes.length-1;i>=0;i--){var t=nodes[i].nodeValue;if(!/\.\s*$/.test(t))continue;var p=t.lastIndexOf('.'),s=document.createElement('span'),f=document.createDocumentFragment();s.className='brand-period';s.textContent='.';f.appendChild(document.createTextNode(t.slice(0,p)));f.appendChild(s);if(t.slice(p+1))f.appendChild(document.createTextNode(t.slice(p+1)));nodes[i].parentNode.replaceChild(f,nodes[i]);break}}document.querySelectorAll('h1,h2').forEach(redPeriod);
});